# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eyecontact.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x65yecontact.proto\x12\x1bnvidia.maxine.eyecontact.v1\x1a\x1bgoogle/protobuf/empty.proto\"\xde\x03\n\x12RedirectGazeConfig\x12\x10\n\x08temporal\x18\x01 \x01(\r\x12\x16\n\x0e\x64\x65tect_closure\x18\x02 \x01(\r\x12\x1c\n\x14\x65ye_size_sensitivity\x18\x03 \x01(\r\x12\x17\n\x0f\x65nable_lookaway\x18\x04 \x01(\r\x12\x1b\n\x13lookaway_max_offset\x18\x05 \x01(\r\x12\x1d\n\x15lookaway_interval_min\x18\x06 \x01(\r\x12\x1f\n\x17lookaway_interval_range\x18\x07 \x01(\r\x12 \n\x18gaze_pitch_threshold_low\x18\x08 \x01(\x02\x12!\n\x19gaze_pitch_threshold_high\x18\t \x01(\x02\x12\x1e\n\x16gaze_yaw_threshold_low\x18\n \x01(\x02\x12\x1f\n\x17gaze_yaw_threshold_high\x18\x0b \x01(\x02\x12 \n\x18head_pitch_threshold_low\x18\x0c \x01(\x02\x12!\n\x19head_pitch_threshold_high\x18\r \x01(\x02\x12\x1e\n\x16head_yaw_threshold_low\x18\x0e \x01(\x02\x12\x1f\n\x17head_yaw_threshold_high\x18\x0f \x01(\x02\"\x83\x01\n\x13RedirectGazeRequest\x12\x41\n\x06\x63onfig\x18\x01 \x01(\x0b\x32/.nvidia.maxine.eyecontact.v1.RedirectGazeConfigH\x00\x12\x19\n\x0fvideo_file_data\x18\x02 \x01(\x0cH\x00\x42\x0e\n\x0cstream_input\"\xb2\x01\n\x14RedirectGazeResponse\x12\x41\n\x06\x63onfig\x18\x01 \x01(\x0b\x32/.nvidia.maxine.eyecontact.v1.RedirectGazeConfigH\x00\x12\x19\n\x0fvideo_file_data\x18\x02 \x01(\x0cH\x00\x12+\n\tkeepalive\x18\x03 \x01(\x0b\x32\x16.google.protobuf.EmptyH\x00\x42\x0f\n\rstream_output2\x94\x01\n\x17MaxineEyeContactService\x12y\n\x0cRedirectGaze\x12\x30.nvidia.maxine.eyecontact.v1.RedirectGazeRequest\x1a\x31.nvidia.maxine.eyecontact.v1.RedirectGazeResponse\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'eyecontact_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REDIRECTGAZECONFIG']._serialized_start=79
  _globals['_REDIRECTGAZECONFIG']._serialized_end=557
  _globals['_REDIRECTGAZEREQUEST']._serialized_start=560
  _globals['_REDIRECTGAZEREQUEST']._serialized_end=691
  _globals['_REDIRECTGAZERESPONSE']._serialized_start=694
  _globals['_REDIRECTGAZERESPONSE']._serialized_end=872
  _globals['_MAXINEEYECONTACTSERVICE']._serialized_start=875
  _globals['_MAXINEEYECONTACTSERVICE']._serialized_end=1023
# @@protoc_insertion_point(module_scope)
